### ISSUE TITLE
Base directory and loading jade files

### ISSUE THREAD

**Issue by bweston92** [pheuter/require-j#3]
Hey,
Is there anyway I could do this:

```
var jade = require("jade");
template  = jade.load("path/to/jade/file");
```

The above is an example that means I wouldn't have to create long dependency arrays or anonymous functions.

Also if I want to change the directory so instead of the base directory for jade files to be the same as require, using a specific directory just for jade files?

**Comment by pheuter** [comment]
> Is there anyway I could do this:

require-j is a RequireJS plugin that is meant to be used in a project that utilizes the RequireJS define/require pattern and usually the [optimizer](http://requirejs.org/docs/optimization.html). With that said, I'm not quiet sure what you mean by the code snippet you provided. The RequireJS way would be to do something like this:

``` javascript
var template = require('j!path/to/jade/file');
```

> if I want to change the directory

You can totally do that. If you take a look at **demo/build-config.js**, you can specify any `baseUrl` you would like, and then your `require` and `define` statements will look for files relative to that directory. Currently, it is set to `.`, the current **demo** directory.

EDIT: You can find more information about all the different configuration options [here](http://requirejs.org/docs/api.html#config)

**Comment by bweston92** [comment]
Many thanks
